[project]
name = "anndata-duckdb-extension"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "black>=24",
    "clang-format==11.0.1",
    "cmake-format>=0.6.13",
]
