#
# Workflow for deploying the extension to S3
# This enables: INSTALL anndata FROM 's3://<your-bucket>';
#
name: Deploy Extension
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to S3
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.3.2
    secrets: inherit
    with:
      extension_name: anndata
      duckdb_version: v1.3.2
      ci_tools_version: v1.3.2
      deploy_latest: true
      deploy_versioned: true
    # Uncomment to enable real deployment (default is dry-run)
    # env:
    #   DUCKDB_DEPLOY_SCRIPT_MODE: for_real