name: Test AWS Secrets
on:
  workflow_dispatch:

jobs:
  test-secrets:
    name: Test Secret Access
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets availability
        run: |
          echo "Testing if GitHub secrets are accessible..."
          echo ""
          
          # Check each secret
          if [ -n "${{ secrets.S3_DUCKDB_ORG_DEPLOY_ID }}" ]; then
            echo "✅ S3_DUCKDB_ORG_DEPLOY_ID is set"
          else
            echo "❌ S3_DUCKDB_ORG_DEPLOY_ID is NOT set or empty"
          fi
          
          if [ -n "${{ secrets.S3_DUCKDB_ORG_DEPLOY_KEY }}" ]; then
            echo "✅ S3_DUCKDB_ORG_DEPLOY_KEY is set"
          else
            echo "❌ S3_DUCKDB_ORG_DEPLOY_KEY is NOT set or empty"
          fi
          
          if [ -n "${{ secrets.S3_DUCKDB_ORG_REGION }}" ]; then
            echo "✅ S3_DUCKDB_ORG_REGION is set"
          else
            echo "❌ S3_DUCKDB_ORG_REGION is NOT set or empty"
          fi
          
          if [ -n "${{ secrets.S3_DUCKDB_ORG_BUCKET }}" ]; then
            echo "✅ S3_DUCKDB_ORG_BUCKET is set"
          else
            echo "❌ S3_DUCKDB_ORG_BUCKET is NOT set or empty"
          fi

      - name: Test AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DUCKDB_ORG_DEPLOY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DUCKDB_ORG_DEPLOY_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_DUCKDB_ORG_REGION }}
        run: |
          echo "Testing AWS credentials..."
          
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "❌ AWS_ACCESS_KEY_ID environment variable is NOT set"
            echo "This is what the deploy script sees - explains 'No AWS key found' error"
          else
            echo "✅ AWS_ACCESS_KEY_ID environment variable is set"
          fi
          
          # Try to list S3 buckets to verify credentials work
          if [ -n "$AWS_ACCESS_KEY_ID" ]; then
            echo ""
            echo "Testing AWS access..."
            pip install awscli --quiet
            if aws s3 ls >/dev/null 2>&1; then
              echo "✅ AWS credentials are valid and working"
              echo "Bucket to use: ${{ secrets.S3_DUCKDB_ORG_BUCKET }}"
            else
              echo "⚠️  AWS credentials might be invalid or have insufficient permissions"
            fi
          fi

  test-deploy-workflow:
    name: Test Deploy Workflow Secrets
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.3.2
    secrets: inherit
    with:
      extension_name: anndata
      duckdb_version: v1.3.2
      ci_tools_version: v1.3.2
      deploy_latest: false
      deploy_versioned: false
      # This will fail at artifact download, but we'll see if secrets are passed